name: Yoni Telegram Reminders

on:
  schedule:
    - cron: '30 6 * * *'      # 08:30 CEST diario
  workflow_dispatch:
    inputs:
      test:
        description: '¿Enviar mensaje de prueba? (true/false)'
        required: false
        default: 'false'

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Yoni reminders
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:       ${{ secrets.CHAT_ID }}
          FORCE_TEST:    ${{ github.event.inputs.test == 'true' && '1' || '0' }}
        run: python reminders.py
